version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: course_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: 1234
    ports:
      - "3311:3306"
    volumes:
      - course-db:/var/lib/mysql

volumes:
  course-db:
