version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: authuser_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: ${REGULAR_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - authuser-db:/var/lib/mysql

volumes:
  authuser-db:
