spring:
  application:
    name: ms-course
  datasource:
    url: jdbc:mysql://localhost:3310/course?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ROOT_USER:root}
    password: ${ROOT_PASSWORD:example}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082

ead:
  api:
    url:
      user: 'http://localhost:8080'
    endpoint: '/v1/users'
